spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mit-auth-server?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name:  com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-active: 10000
        max-idle: 50
        max-wait: -1
        min-idle: 0

  main:
    allow-bean-definition-overriding: true

# feign远程调用配置
feign:
  hystrix:
    # 开启熔断
    enabled: true
